- name: Create OpenShift Installation Directory and Prereqs
  hosts: localhost
  become: true
  become_user: "{{ student_name }}"
  vars_files:
  - vars.yml
  tasks:
  - name: Create /home/{{ student_name }}/ocpinstall/install/
    ansible.builtin.file:
      path: /home/{{ student_name }}/ocpinstall/install/
      state: directory

  - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
    ansible.builtin.openssh_keypair:
      path: /home/{{ student_name }}/ocpinstall/install/id_rsa
    register: keypair
  - name: Generate install-config.yaml
    ansible.builtin.template:
      src: install-config.yaml.j2
      dest: /home/{{ student_name }}/ocpinstall/install/install-config.yaml
    vars:
      sshKey_content: "{{ keypair.public_key }}"

  - name: Generate install-config.yaml.back
    ansible.builtin.template:
      src: install-config.yaml.j2
      dest: /home/{{ student_name }}/ocpinstall/install/install-config.yaml.back
    vars:
      sshKey_content: "{{ keypair.public_key }}"

  - name: Create manifests and replace some content
    ansible.builtin.shell:
      cmd: "{{ item }}"
      chdir: "/home/{{ student_name }}/ocpinstall/install/"
    loop:
    - "/usr/local/bin/openshift-install create manifests --dir ~/ocpinstall/install/ --log-level debug"
    - "rm -f openshift/99_openshift-cluster-api_master-machines-*.yaml openshift/99_openshift-cluster-api_worker-machineset-*.yaml"
    - "sed -i 's/mastersSchedulable: true/mastersSchedulable: false/' manifests/cluster-scheduler-02-config.yml"
